#!/usr/bin/env php
<?php

use Lucid\Commands\ControllerMakeCommand;
use Lucid\Commands\FeatureMakeCommand;
use Lucid\Commands\JobMakeCommand;
use Lucid\Commands\ServiceMakeCommand;

if (file_exists('./vendor/autoload.php')) {
    require './vendor/autoload.php';
} else if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
}

if (file_exists('./bootstrap/app.php')) {
    $laravel = require './bootstrap/app.php';
} else {
    $laravel = require __DIR__ . '/../../../bootstrap/app.php';
}

$commands = [
    new ServiceMakeCommand(),
    new ControllerMakeCommand(),
    new JobMakeCommand(),
    new FeatureMakeCommand()
];

$app = new Symfony\Component\Console\Application('Lucid', '1.0.0');
array_walk($commands, [$app, 'add']);

$app->run();
